server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl: #Eureka Server注册中心的地址，用于client与server进行交流
     # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  application:
    name: eureka-service
