---
spring:
  profiles: peer1
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl: #Eureka Server注册中心的地址，用于client与server进行交流
      defaultZone: http://localhost:8760/eureka
  server:
    enable-self-preservation: false


---
spring:
  profiles: peer2
  application:
    name: eureka-service

server:
  port: 8760

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    enable-self-preservation: false
---

spring:
  profiles:
    active: peer2