server:
  port: 8762

spring:
  application:
    name: eureka-client-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.35.132/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka, http://localhost:8760/eureka

