server:
  port: 8763

spring:
  application:
    name: service-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka, http://localhost:8760/eureka

eureka-client-service:
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule